# Copyright (c) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2016-present Sven Greb <code@svengreb.de>

# Project:    Nord Hyper
# Repository: https://github.com/arcticicestudio/nord-hyper
# License:    MIT
# References:
#   https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
node_js:
  - "6"
  - "4"
cache: yarn
before_script:
  - yarn global add gulp
  - yarn install
script: gulp --harmony lint
